version: '3'

# Définir les services
services:
  #Jenkins
  jenkins:
    # Image de Jenkins -> Fichier Dockerfile à la racine
    build: .
    # Nom du container
    container_name: my_marvin_jenkins
    # Port d'écoute
    ports:
      - "8080:8080"
      - "50000:50000"
    # Renseigner le fichier environnement
    env_file: .env
    # Les volumes pour la sauvegarde des données
    volumes:
      - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home: