# Définir les services
services:
  #Jenkins
  jenkins:
    # Image de Jenkins -> Fichier Dockerfile à la racine
    build: .
    # Nom du container
    container_name: my_marvin_jenkins
    # Port d'écoute
    ports:
      - "8080:8080"
    # Les volumes pour la sauvegarde des données
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc_configs
      #- JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    volumes:
      - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home: