# Docker compose pour gérer les éxecutions des services
version: '3'
# Définir les services
services:
  #Jenkins
  jenkins:
    # Image de Jenkins -> Fichier Dockerfile à la racine
    build: .
    # Nom du container
    container_name: my_marvin_jenkins
    # Port d'écoute
    ports:
      - "8080:8080"
    # Les volumes pour la sauvegarde des données
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./my_marvin.yml:/var/jenkins_home/casc_configs/my_marvin.yml
      - ./job_dsl.groovy:/var/jenkins_home/init.groovy.d/job_dsl.groovy

volumes:
  jenkins_home: